stages:
  clean_data:
    cmd: python -c "from src.data_loader import load_data; df = load_data('data/insurance_data.csv'); df.drop_duplicates().to_csv('data/insurance_data_clean.csv', index=False)"
    deps:
      - data/insurance_data.csv
      - src/data_loader.py
    outs:
      - data/insurance_data_clean.csv
